In [4]:
from bo_functions import LHS_Design
from bo_functions import create_y_data
from bo_functions import calc_y_exp
from bo_functions import test_train_split
from bo_functions import create_sse_data
import numpy as np
import pandas as pd

In [5]:
#Creates Experimental data and saves to a csv
Theta_True = np.array([1,-1])
Xexp = np.array([-2,-1,0,1,2])
noise_std = 0.1**2

Yexp = calc_y_exp(Theta_True, Xexp, noise_std)

Exp_data = np.column_stack((Xexp,Yexp))
df = pd.DataFrame(Exp_data, columns = ["Xexp","Yexp"])
df.to_csv('exp_data.csv')

In [6]:
#Create Training Data and Testing Data
#Set noise parameters and load csv file to generate training data
all_p = LHS_Design("LHS_Toy_3_Input.csv")
all_2_in_y = create_sse_data(all_p,Xexp,Yexp)
all_3_in_y = create_y_data(all_p)

#Separate training and testing data, uses default of an 80%/20% split
train_test_data_3_in = test_train_split(all_p,all_3_in_y)
train_test_data_2_in = test_train_split(all_p,all_2_in_y)

train_p = train_test_data_3_in[0] #1x19
test_p = train_test_data_3_in[2] #1x6


train_y_3_in = train_test_data_3_in[1] #1x19
test_y_3_in = train_test_data_3_in[3] #1x6

train_y_2_in = train_test_data_2_in[1] #1x19
test_y_2_in = train_test_data_2_in[3] #1x6


#Save Train Data
train_3_input = np.column_stack((train_p, train_y_3_in))

df = pd.DataFrame(train_3_input, columns = ["Theta_1","Theta_2","X Coord","y-value"])
df.to_csv('train_3_in_data.csv')

train_2_input = np.column_stack((train_p[:,0], train_p[:,1], train_y_2_in))

df = pd.DataFrame(train_2_input, columns = ["Theta_1","Theta_2","y-value"])
df.to_csv('train_2_in_data.csv')


#Save Test Data
test_3_input = np.column_stack((test_p, test_y_3_in))

df = pd.DataFrame(test_3_input, columns = ["Theta_1","Theta_2","X Coord","y-value"])
df.to_csv('test_3_in_data.csv')

test_2_input = np.column_stack((test_p[:,0], test_p[:,1], test_y_2_in))

df = pd.DataFrame(test_2_input, columns = ["Theta_1","Theta_2","y-value"])
df.to_csv('test_2_in_data.csv')

In [9]:
#LHS Design in python - May switch code to use this instead for conciseness
from scipy.stats import qmc
sampler = qmc.LatinHypercube(d=3)
sample = sampler.random(n=25)
l_bounds =  [-2, -2,-2]
u_bounds =  [2, 2,2]
x = qmc.scale(sample, l_bounds, u_bounds)
print(x)

[[ 0.36780794 -1.97603283 -0.63791734]
 [-1.94103156  1.07115317  1.80496556]
 [-0.83394824  1.28323581  0.52924173]
 [-0.06116551 -1.10218735  1.09632691]
 [-0.6530426  -1.73193345 -0.55416903]
 [-0.18411185  0.6022007  -1.97466435]
 [ 1.15823989  0.75672061  1.49186482]
 [-1.6844904  -1.62919952  1.02718984]
 [ 0.12598931 -1.38682054 -1.31591621]
 [ 1.98935871  1.02636501  0.78937174]
 [ 0.6988896  -1.31575487 -0.12463738]
 [ 1.03409591 -1.00033086 -0.25533279]
 [ 1.24258742 -0.31854658 -0.06978577]
 [ 0.86130015 -0.53732335 -1.10414572]
 [ 1.59822191  0.0373301  -1.39832877]
 [-1.5254236  -0.12196108 -1.57237667]
 [ 1.73590032  1.79395895 -0.85258861]
 [-1.48478821  1.42890661  0.17278001]
 [ 0.47952104  0.51224027  1.97013897]
 [-1.17432194  1.84685228  0.66597354]
 [-0.96687099 -0.73577179  0.33655868]
 [-0.46345667  0.31205539 -0.96541172]
 [-0.29589459  1.5220118   1.34462906]
 [ 1.4410053  -0.70019077 -1.75453581]
 [-1.35786289  0.17357954  1.6144547 ]]
