In [8]:
import gpytorch
import numpy as np
import pandas as pd
import torch
from datetime import datetime
import datetime
from itertools import combinations_with_replacement
from itertools import combinations
from itertools import permutations
from scipy.stats import qmc

import matplotlib as mpl
mpl.rcParams['figure.dpi'] = 300

In [13]:
from sklearn.preprocessing import MinMaxScaler
X = np.array([[1,-6,2],
     [6,7,3],
     [3, 23,12],
     [3, 12,17]])

from sklearn.model_selection import LeaveOneOut

y_true  = []
y_pred = []

print(loo.get_n_splits(X))
for train_index, test_index in loo.split(X):
    df_test = X[test_index]
    df_train = X[train_index]
    print(df_train, df_test)
    

# scaler =  MinMaxScaler()
# scaler.fit(X)
# X = scaler.transform(X)
# X = scaler.inverse_transform(X)
# print(X)

4
[[ 6  7  3]
 [ 3 23 12]
 [ 3 12 17]] [[ 1 -6  2]]
[[ 1 -6  2]
 [ 3 23 12]
 [ 3 12 17]] [[6 7 3]]
[[ 1 -6  2]
 [ 6  7  3]
 [ 3 12 17]] [[ 3 23 12]]
[[ 1 -6  2]
 [ 6  7  3]
 [ 3 23 12]] [[ 3 12 17]]


In [51]:
# https://realpython.com/python-timer/
import time
start = 3678393
res = datetime.timedelta(seconds =start)
print(res)

time_tot = 0
x = 0
for i in range(89900):
    start2 = time.time()
    x += 1+2
    end = time.time()

    time_tot+= (end - start2)


print(time_tot)

42 days, 13:46:33
0.016117095947265625


In [26]:
A = np.array([[4,3,0,0],
              [4,0,0,3]])
print(A[np.nonzero(A)])

[4 3 4 3]


In [16]:
B = np.zeros((3,3))
B = pd.DataFrame(B)
type(B)
isinstance(B, pd.DataFrame)

True

In [11]:
np.random.seed(9)
Array_1 = np.random.rand(3,2)
Array_2 = np.random.rand(3,2)

print(Array_1)
print(Array_2)

ds = gdal.Open('image.tif')
# loop through each band

path = 

with open("converted.raw", "wb") as outfile:
    for bi in range(ds.RasterCount):
        band = ds.GetRasterBand(bi + 1)
        # Read this band into a 2D NumPy array
        ar = band.ReadAsArray()
        print('Band %d has type %s'%(bi + 1, ar.dtype))   
        np.save(outfile, ar.astype('uint16'))

[[0.01037415 0.50187459]
 [0.49577329 0.13382953]
 [0.14211109 0.21855868]]
[[0.41850818 0.24810117]
 [0.08405965 0.34549864]
 [0.16677635 0.87855909]]
