In [1]:
import gpytorch
import numpy as np
import pandas as pd
import torch
from datetime import datetime

from bo_functions import bo_iter_w_runs
from bo_functions import find_train_doc_path
from bo_functions import set_ep
from bo_plotters import save_csv
import os

import matplotlib as mpl
mpl.rcParams['figure.dpi'] = 300

/afs/crc.nd.edu/user/m/mcarlozo/.conda/envs/Toy_Problem_env/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
Array = np.array([[1,2,2],[1,2,3]])
Array = pd.DataFrame(Array, columns = ['Column_A','Column_B','Column_C'])
path = save_csv(Array, "Test_folder/Test", ext = "csv")

FileExistsError: [Errno 17] File exists: 'Test_folder'

In [ ]:

print(path)

In [3]:
p_true = np.array([1,-1])
x_space = np.array([-2,-1,0,1,2])
len_x = len(x_space)
p_true_3D = np.repeat(p_true,len_x).reshape(-1,len_x).T
print(p_true_3D)
p_true_3D_full = np.hstack((p_true_3D, x_space.reshape(len_x,-1)))
print(p_true_3D_full)

[[ 1 -1]
 [ 1 -1]
 [ 1 -1]
 [ 1 -1]
 [ 1 -1]]
[[ 1 -1 -2]
 [ 1 -1 -1]
 [ 1 -1  0]
 [ 1 -1  1]
 [ 1 -1  2]]
